### ISSUE TITLE
TypeError: Cannot read property 'simplifySparqlResults' of undefined

### ISSUE THREAD

**Issue by waldyrious** [maxlath/wikidata-cli#19]
I just installed wikidata-cli using `npm install -g wikidata-cli`, and tried doing `wd s Q186055`. Here's the output:

```
Label git
Description free and open source revision control software
TypeError: Cannot read property 'simplifySparqlResults' of undefined
    at body (/usr/local/lib/node_modules/wikidata-cli/lib/fetch_lang_props.js:22:6)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Context: undefined
```

**Comment by maxlath** [comment]
@waldyrious thanks !! I just published the patch: v4.8.2
