### ISSUE TITLE
plain wd config fails if no key has been defined

### ISSUE THREAD

**Issue by waldyrious** [maxlath/wikidata-cli#20]
```
$ wd config
/usr/local/lib/node_modules/wikidata-cli/bin/wd-config:13
  config.password = config.password.replace(/./g, '*')
                                   ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/wikidata-cli/bin/wd-config:13:36)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by maxlath** [comment]
thanks!

**Comment by waldyrious** [comment]
That was fast! Thank you :)

**Comment by maxlath** [comment]
my pleasure!
