### ISSUE TITLE
Cannot read property 'W_OK' of undefined

### ISSUE THREAD

**Issue by mrkev** [maxlath/wikidata-cli#23]
Running `wd s Q1` gives me the following issue on version 4.8.3

```
~/.nvm/versions/node/v6.2.2/lib/node_modules/wikidata-cli/lib/get_folder_path.js:17
    if (err.code !== 'EACCES') throw err
                               ^

TypeError: Cannot read property 'W_OK' of undefined
    at Object.module.exports.writeAccessSync (/Users/Kevin/.nvm/versions/node/v6.2.2/lib/node_modules/wikidata-cli/lib/fs.js:26:37)
    at module.exports (/Users/Kevin/.nvm/versions/node/v6.2.2/lib/node_modules/wikidata-cli/lib/get_folder_path.js:15:8)
    at Object.<anonymous> (/Users/Kevin/.nvm/versions/node/v6.2.2/lib/node_modules/wikidata-cli/lib/get_cache_folder_path.js:2:49)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by maxlath** [comment]
oh, it seems `fs.constants` is a quite recent object as it doesn't exist for Node `v6.2.2`.
So the problem should disappear if you upgrade to a version above `v6.4.0` (where the LTS support started), but I guess that should be made more obvious when running `wikidata-cli`, maybe by testing node version and exiting if it isn't >= v6.4

**Comment by mrkev** [comment]
Yup! Upgrading node solved it! I just noticed that `package.json` does specify that the minimum supported version of node is `6.9.1`, but I don't get any warning whatsoever when I install it using npm. A notice would be nice, if not when running the package, at least on the readme (:

**Comment by maxlath** [comment]
I made it more explicit in the readme (2efa18c) and run a check during postinstall (e03d49f)

**Comment by mrkev** [comment]
Awesome, thanks!
