### ISSUE TITLE
TypeError: url.replace is not a function

### ISSUE THREAD

**Issue by almereyda** [maxlath/wikidata-cli#43]
When querying against a custom Wikibase instance, the following error occurs:

```
$ wd config instance https://base.transformap.co/api.php  
$ wd summary Q218                                       
Label Ziele für nachhaltige Entwicklung
Description Die Ziele für nachhaltige Entwicklung sind politische Zielsetzungen der Vereinten Nationen (UN), die der Sicherung einer nachhaltigen Entwicklung auf ökonomischer, sozialer sowie ökologischer Ebene dienen sollen. Die Ziele wurden in Anlehnung an den Entwicklungsprozess der Millenniums-Entwicklungsziele (MDGs) entworfen und traten am 1. Januar 2016 mit einer Laufzeit von 15 Jahren (bis 2030) in Kraft. Im Unterschied zu den MDGs, die insbesondere Entwicklungsländern galten, gelten die SDGs für alle Staaten.
TypeError: url.replace is not a function
    at unwww (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/custom_wikibase_instance.js:22:28)
    at customize (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/custom_wikibase_instance.js:24:28)
    at Object.wdk.customize (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/customized_wdk.js:11:27)
    at ids (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/get_labels.js:12:22)
    at module.exports (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/log_claims.js:11:5)
Context: undefined
```

**Comment by maxlath** [comment]
fixed by 6c2f75c and published in `v5.4.0`
