### ISSUE TITLE
Error when searching using verbose mode

### ISSUE THREAD

**Issue by palancana** [maxlath/wikidata-cli#56]
```wd search Pere Dot Martinez -v
{ Error: Command failed: /bin/sh -c export FORCE_COLOR=true; /usr/local/node_modules/wikidata-cli/lib/bin/wd summary Q7159553 --lang es
/bin/sh: /usr/local/node_modules/wikidata-cli/lib/bin/wd: No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c export FORCE_COLOR=true; /usr/local/node_modules/wikidata-cli/lib/bin/wd summary Q7159553 --lang es',
  stdout: '',
  stderr: '/bin/sh: /usr/local/node_modules/wikidata-cli/lib/bin/wd: No such file or directory\n' }```

**Comment by maxlath** [comment]
thanks @palancana! that should be fixed in `v6.0.8`, you can test it by running:
```sh
npm i -g wikidata-cli@latest
wd search Pere dot martinez -v
```
