### ISSUE TITLE
support piping

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-cli#7]
In the commander branch

```
./bin/wd data Q1 | head
{
    "pageid": 129,
    "ns": 0,
    "title": "Q1",
    "lastrevid": 369618258,
    "modified": "2016-08-26T03:50:30Z",
    "type": "item",
    "id": "Q1",
    "labels": {
        "en": {
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

**Comment by maxlath** [comment]
this seems to be a [known issue in node](https://github.com/nodejs/node/issues/947) but with no clear solution
